/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface MissedHour {
  class: string;
  class_group: string | null;
  created_at: Generated<Timestamp>;
  date: Timestamp;
  discipline: string | null;
  nb_hours: number;
  school_id: string;
  uuid: string;
}

export interface Task {
  id: Generated<number>;
  priority: Generated<number>;
  title: string;
}

export interface DB {
  missed_hour: MissedHour;
  task: Task;
}
