/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface MissedHour {
  class: string;
  class_group: string | null;
  created_at: Generated<Timestamp>;
  date: Timestamp;
  departement: string | null;
  discipline: string | null;
  id: Generated<number>;
  nb_hours: number;
  school_id: string;
}

export interface MissedHourEvent {
  class: string | null;
  class_group: string | null;
  date: Timestamp | null;
  departement: string | null;
  discipline: string | null;
  first_reported_at: Timestamp | null;
  last_reported_at: Timestamp | null;
  nb_hours: number | null;
  school_id: string | null;
  submissions: Int8 | null;
}

export interface DB {
  missed_hour: MissedHour;
  missed_hour_event: MissedHourEvent;
}
